name: Testcontainers Integration Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      docker:
        image: docker:20.10.24
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0' # Kies de juiste versie voor jouw project

    - name: Install dependencies
      run: dotnet restore PridrIntergrationTest/PridrIntergrationTest.csproj

    - name: Run integration tests with detailed output
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      run: dotnet test PridrIntergrationTest/PridrIntergrationTest.csproj --logger "console;verbosity=detailed"
      
    - name: Set status on success
      if: success()
      run: echo "✅ Integration tests passed!"

    - name: Set status on failure
      if: failure()
      run: echo "❌ Integration tests failed!"
      
    - name: Upload Test Results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ./TestResults/

