name: Testcontainers Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.24
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0' # Kies de juiste versie voor jouw project

    - name: Install dependencies
      run: dotnet restore PridrIntergrationTest/PridrIntergrationTest.csproj

    - name: Run integration tests
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      run: dotnet test PridrIntergrationTest/PridrIntergrationTest.csproj
